/**
 * properties-data.js
 * Centralized property data store for Marci Metzger Homes.
 * Defines all 12 curated Southern Nevada properties.
 */

const PROPERTIES_DATA = [
  {
    id: "golf-community-villa",
    title: "Golf Community Villa",
    location: "Mountain Falls, Pahrump",
    locationSlug: "pahrump mountain-falls",
    price: 685000,
    priceFormatted: "$685,000",
    beds: 4,
    baths: 3,
    sqft: 3120,
    sqftFormatted: "3,120 SQ FT",
    type: "residential",
    image: "Asset/Photo Gallery/7.webp",
    alt: "Mountain Falls Golf Community Villa in Pahrump, Nevada",
    description:
      "Nestled within the premier Mountain Falls golf community, this refined villa blends luxury and low-maintenance desert living. Features expansive open living spaces, granite countertops, primary suite with spa-inspired bath, and an oversized covered patio overlooking serene greens.",
    features: [
      "Mountain Falls Golf Club Access",
      "Custom Granite Kitchen",
      "Covered Entertainer Patio",
      "Dual Primary Suites",
      "3-Car Garage",
    ],
    isExtra: false,
  },
  {
    id: "desert-foothills-estate",
    title: "Desert Foothills Estate",
    location: "Southern Nevada",
    locationSlug: "southern-nevada pahrump",
    price: 1250000,
    priceFormatted: "$1,250,000",
    beds: 5,
    baths: 5,
    sqft: 4850,
    sqftFormatted: "4,850 SQ FT",
    type: "residential",
    image: "Asset/Photo Gallery/4.webp",
    alt: "Desert Foothills Custom Pool Estate in Southern Nevada",
    description:
      "A dramatic private desert compound situated against the majestic Spring Mountain backdrop. Offering resort-level amenities including an infinity-edge heated pool, detached guest casita, high-beamed ceilings, and sweeping 360-degree desert panoramas.",
    features: [
      "Private Heated Pool & Spa",
      "Detached Guest Casita",
      "1.5 Acre Gated Parcel",
      "Outdoor Summer Kitchen",
      "4-Car Motor Court",
    ],
    isExtra: false,
  },
  {
    id: "beacon-ridge-residence",
    title: "Beacon Ridge Residence",
    location: "Pahrump, NV",
    locationSlug: "pahrump",
    price: 540000,
    priceFormatted: "$540,000",
    beds: 3,
    baths: 3,
    sqft: 2650,
    sqftFormatted: "2,650 SQ FT",
    type: "residential",
    image: "Asset/Photo Gallery/3.webp",
    alt: "Beacon Ridge Custom Residence in Pahrump, Nevada",
    description:
      "Positioned on an elevated view lot along Beacon Ridge, this custom single-story residence boasts sunlit living areas, tile throughout common spaces, a gourmet kitchen with center preparation island, and a private rear sanctuary with unobstructed sunset vistas.",
    features: [
      "Elevated Sunset Lot",
      "Gourmet Prep Island",
      "Energy-Efficient HVAC",
      "Custom Built-in Cabinetry",
      "Extended RV Parking",
    ],
    isExtra: false,
  },
  {
    id: "spanish-palms-villa",
    title: "Spanish Palms Villa",
    location: "Pahrump, NV",
    locationSlug: "pahrump",
    price: 895000,
    priceFormatted: "$895,000",
    beds: 4,
    baths: 3.5,
    sqft: 3680,
    sqftFormatted: "3,680 SQ FT",
    type: "residential",
    image: "Asset/Guide Section/2.webp",
    alt: "Spanish Palms luxury villa with illuminated swimming pool in Pahrump, Nevada",
    description:
      "Spanish architectural elegance with contemporary finishes. Enjoy an illuminated private swimming pool with cascading water features, Mediterranean courtyard entry, dramatic arched windows, and a master retreat with dual walk-in closets.",
    features: [
      "Illuminated In-Ground Pool",
      "Courtyard Entry Fountain",
      "Arched Architectural Windows",
      "Dual Primary Closets",
      "Owned Solar System",
    ],
    isExtra: false,
  },
  {
    id: "artesia-ranch-contemporary",
    title: "Artesia Ranch Contemporary",
    location: "Artesia, Pahrump",
    locationSlug: "artesia pahrump",
    price: 475000,
    priceFormatted: "$475,000",
    beds: 3,
    baths: 2.5,
    sqft: 2240,
    sqftFormatted: "2,240 SQ FT",
    type: "residential",
    image: "Asset/Our Service/2.webp",
    alt: "Artesia Ranch contemporary residence with lawn and pool in Pahrump, Nevada",
    description:
      "Located in the desirable Artesia neighborhood, this contemporary home delivers effortless curb appeal and functional design. Features a manicured green lawn, private plunge pool, open-concept great room, and quiet community park access.",
    features: [
      "Private Backyard Plunge Pool",
      "Open Concept Great Room",
      "Low HOA Community",
      "Walking Distance to Parks",
      "Turnkey Condition",
    ],
    isExtra: false,
  },
  {
    id: "fairways-waterfront-estate",
    title: "Fairways Waterfront Estate",
    location: "Mountain Falls, Pahrump",
    locationSlug: "mountain-falls pahrump",
    price: 1450000,
    priceFormatted: "$1,450,000",
    beds: 5,
    baths: 4.5,
    sqft: 5120,
    sqftFormatted: "5,120 SQ FT",
    type: "residential",
    image: "Asset/Photo Gallery/1.webp",
    alt: "The Fairways waterfront golf estate overlooking Mountain Falls lake in Pahrump, Nevada",
    description:
      "The crowning jewel of Mountain Falls waterfront estates. Positioned directly on the scenic lake overlooking the fairway, this grand residence features floor-to-ceiling windows, professional chef's kitchen, private dock access, and palatial terrace entertaining.",
    features: [
      "Direct Waterfront Lake Access",
      "Championship Golf Views",
      "Sub-Zero & Wolf Appliances",
      "Private Lakeside Terrace",
      "3-Car Tandem Garage",
    ],
    isExtra: false,
  },
  {
    id: "sunroom-desert-retreat",
    title: "Sunroom Desert Retreat",
    location: "Pahrump, NV",
    locationSlug: "pahrump",
    price: 599000,
    priceFormatted: "$599,000",
    beds: 3,
    baths: 2.5,
    sqft: 2890,
    sqftFormatted: "2,890 SQ FT",
    type: "residential",
    image: "Asset/Photo Gallery/2.webp",
    alt: "Sunroom Desert Retreat with panoramic glass windows in Pahrump, Nevada",
    description:
      "Architectural retreat featuring a sun-drenched enclosed solarium and glass sunroom with wraparound desert mountain views. Perfect for morning yoga or entertaining under starry Nevada skies.",
    features: [
      "Glass Enclosed Solarium",
      "Wraparound Mountain Views",
      "Xeriscape Low-Water Landscaping",
      "Gas Fireplace Feature",
      "Oversized Workshop",
    ],
    isExtra: true,
  },
  {
    id: "mountain-falls-club-residence",
    title: "Mountain Falls Club Residence",
    location: "Mountain Falls, Pahrump",
    locationSlug: "mountain-falls pahrump",
    price: 785000,
    priceFormatted: "$785,000",
    beds: 4,
    baths: 4,
    sqft: 3450,
    sqftFormatted: "3,450 SQ FT",
    type: "residential",
    image: "Asset/Photo Gallery/5.webp",
    alt: "Mountain Falls Club Residence near clubhouse in Pahrump, Nevada",
    description:
      "Situated just footsteps from the Mountain Falls Clubhouse and Grill, this executive golf residence boasts soaring coffered ceilings, travertine flooring, wet bar, and an expansive covered loggia overlooking lush greens.",
    features: [
      "Steps to Clubhouse & Dining",
      "Soaring Coffered Ceilings",
      "Built-in Entertaining Wet Bar",
      "Travertine Stone Flooring",
      "Golf Cart Garage",
    ],
    isExtra: true,
  },
  {
    id: "rustic-ridge-ranch",
    title: "Rustic Ridge Ranch",
    location: "Southern Nevada",
    locationSlug: "southern-nevada pahrump",
    price: 920000,
    priceFormatted: "$920,000",
    beds: 4,
    baths: 3.5,
    sqft: 3920,
    sqftFormatted: "3,920 SQ FT",
    type: "residential",
    image: "Asset/Guide Section/3.webp",
    alt: "Rustic Ridge Ranch craftsman timber estate in Southern Nevada",
    description:
      "Custom craftsman estate blending rustic timber beams with refined modern comfort. Set on sprawling acreage suited for equestrian facilities or custom workshops, featuring a double-sided stone hearth and custom cedar porch.",
    features: [
      "Custom Timber Beam Construction",
      "Double-Sided Stone Fireplace",
      "Equestrian Acreage Potential",
      "Custom Cedar Porch",
      "Secure Gated Access",
    ],
    isExtra: true,
  },
  {
    id: "grand-chefs-contemporary",
    title: "The Grand Chef's Contemporary",
    location: "Artesia, Pahrump",
    locationSlug: "artesia pahrump",
    price: 645000,
    priceFormatted: "$645,000",
    beds: 3,
    baths: 3,
    sqft: 2980,
    sqftFormatted: "2,980 SQ FT",
    type: "residential",
    image: "Asset/Guide Section/1.webp",
    alt: "The Grand Chef's Contemporary interior kitchen and living in Artesia, Pahrump",
    description:
      "An entertainer's dream showcasing a statement gourmet kitchen with double waterfall islands, custom shaker cabinetry, wine cooler, and seamlessly integrated indoor-outdoor sliding glass pocket doors.",
    features: [
      "Double Quartz Waterfall Islands",
      "Commercial Grade Appliances",
      "Pocket Sliding Glass Doors",
      "Temperature Controlled Wine Wall",
      "Spa Primary Bath",
    ],
    isExtra: true,
  },
  {
    id: "reserve-court-estate",
    title: "The Reserve Court Estate",
    location: "Mountain Falls, Pahrump",
    locationSlug: "mountain-falls pahrump",
    price: 1180000,
    priceFormatted: "$1,180,000",
    beds: 5,
    baths: 4,
    sqft: 4600,
    sqftFormatted: "4,600 SQ FT",
    type: "residential",
    image: "Asset/Photo Gallery/6.webp",
    alt: "The Reserve Court Estate near tennis courts in Mountain Falls, Pahrump",
    description:
      "Premier sports and leisure estate situated alongside private tennis and pickleball courts. Boasts dual master suites, high-volume ceilings, private courtyard, and direct golf course fairway frontage.",
    features: [
      "Private Tennis & Pickleball Access",
      "Dual Primary Suites",
      "Direct Fairway Frontage",
      "Private Central Courtyard",
      "4-Car Split Garage",
    ],
    isExtra: true,
  },
  {
    id: "desert-modern-sanctuary",
    title: "Desert Modern Sanctuary",
    location: "Pahrump, NV",
    locationSlug: "pahrump",
    price: 515000,
    priceFormatted: "$515,000",
    beds: 3,
    baths: 2,
    sqft: 2420,
    sqftFormatted: "2,420 SQ FT",
    type: "residential",
    image: "Asset/Our Service/1.webp",
    alt: "Desert Modern Sanctuary contemporary living space in Pahrump, Nevada",
    description:
      "Warm minimalist sanctuary crafted with clean lines, polished concrete and wide plank floors, energy-efficient solar orientation, and an intimate walled zen courtyard framed by desert flora.",
    features: [
      "Warm Minimalist Architecture",
      "Private Walled Zen Courtyard",
      "Solar Ready High Efficiency",
      "Polished Finish Flooring",
      "Covered Sunset Lanai",
    ],
    isExtra: true,
  },
];

// Attach to window for global access across scripts
if (typeof window !== "undefined") {
  window.PROPERTIES_DATA = PROPERTIES_DATA;
}
if (typeof module !== "undefined" && module.exports) {
  module.exports = PROPERTIES_DATA;
}
